### ISSUE TITLE
Scrumblr Down ??

### ISSUE THREAD

**Issue by steevebecker** [aliasaria/scrumblr#101]
Hi
I was using Scrumblr.ca since a month, now it's down. Are you aware ?

**Comment by ocdtrekkie** [comment]
Given that I think the author has more or less abandoned this project (inactive 11 months from the look of it?), it probably isn't smart to assume his website will always be up! There are other places you can host Scrumblrs too. I ported it to Sandstorm, and that will let you download backups and stuff of your boards. (oasis.sandstorm.io is free for a limited quantity of instances, FWIW.)
