### ISSUE TITLE
Issue while running node server.js --port 80

### ISSUE THREAD

**Issue by sanjogpandasp** [aliasaria/scrumblr#103]
![screen shot 2017-02-06 at 10 15 41 pm](https://cloud.githubusercontent.com/assets/5404943/22656643/fc7bf04e-ecb9-11e6-98ff-b72363c93d2d.png)

Please refer to the screenshot attached.

**Comment by x8-999-github** [comment]
Running on port 80 probably required admin privileges...

**Comment by nickeeromo** [comment]
I had a similar problem a long time ago with a different program.  I believe it was that port 80 was already listening / used by another process.
