### ISSUE TITLE
http://scrumblr.ca/ no more reachable 

### ISSUE THREAD

**Issue by quest831** [aliasaria/scrumblr#104]
Hi,
I created a board and it is not reachable anymore. Also the http://scrumblr.ca/ website seams down.
Can you help me?
Thanks

**Comment by dalibortoth** [comment]
Hi Ali,
thank you very much for the scrumblr.ca tool - I used it for the first time 2 weeks ago and it worked perfectly. I wanted to use it again today, but the site scrumblr.ca can't be currently reached.

Will be the site http://scrumblr.ca/ available again?

Or is there any possibility I could get to my work in progress on two boards?

Thanks in advance,
Dalibor

**Comment by ocdtrekkie** [comment]
Hey guys, as a note, Aliasaria has not been active on this GitHub repository in a long time. I know that Scrumblr.ca has gone down before and come back up later, so all hope is not lost. But I would generally recommend that you find a safer place to store your data.

Sandstorm Oasis (https://oasis.sandstorm.io) has a Scrumblr app and is free for up to five boards (or files from other apps). And Framemo (https://framemo.org/) which is translated to French, which is free to use. The Sandstorm version of Scrumblr, as well as Framemo both offer ways to download or export your boards as a backup as well. (And a future version of the Sandstorm version will add the ability for you to use those import and export options back and forth with the Framemo version.)

**Comment by ocdtrekkie** [comment]
I suspect the domain name was allowed to lapse, since it's expiry date would've been just a couple weeks ago. The whois looks reminiscent of how one might look after the registrar has taken over the domain:

Domain name:           scrumblr.ca
Domain status:         registered
Creation date:         2011/03/09
Expiry date:           2021/03/09
Updated date:          2017/03/06
DNSSEC:                Unsigned

Registrar:
    Name:              Register.ca Inc.
    Number:            1199886

**Comment by quest831** [comment]
Hi, 
thanks a lot for your update. 
Sorry if I ask it,  but what it does mean? Do you think that will be no chance to have it live again?
Thanks

**Comment by ocdtrekkie** [comment]
@quest831 It's surely possible for Aliasaria to fix it, but _only_ Aliasaria can fix it.

**Comment by dhhhawley** [comment]
It is back up now!   Thank you to whomever resolved the issue

**Comment by aliasaria** [comment]
Sorry everyone. I was traveling when it happened.

**Comment by dalibortoth** [comment]
Thank you very much, Ali!

**Comment by jcorpusg** [comment]
Scrumblr downed again. Since today, August the 22nd.

**Comment by Martin819** [comment]
It looks like the webpage is down again. 
@aliasaria could you please do something? Thank you very much for your work.
