### ISSUE TITLE
Redis with "requirepass"

### ISSUE THREAD

**Issue by msvp** [aliasaria/scrumblr#108]
Hello  from France !

Is it possible to configure Scrumblr to use a REDIS bdd with a requirepass active ?
If so, how ?

Thanks !

**Comment by RedWhiteMiko** [comment]
I haven't tested but adding `client.auth(password, callback)` in https://github.com/aliasaria/scrumblr/blob/master/lib/data/redis.js#L23 should solve it, 
probably need to do the same for reconnect event.
