### ISSUE TITLE
can not use 100% of board

### ISSUE THREAD

**Issue by Jewest** [aliasaria/scrumblr#109]
For some reason I can not use the last 10% of the board.
In my case that's the done section(50% usabel)
The labels will no go to the far right hand side.
making this wonderful tool less usable.

Chrome browser.
screen resolution : 2560 x 1600

**Comment by nickeeromo** [comment]
In index.jade:

`			table#board-table.board-table
				tr
					td#icon-col(width='1%')
						image#add-col.col-icon(width='20', height='20', src='images/icons/iconic/raster/black/plus_alt_32x32.png')
						image#delete-col.col-icon(width='20', height='20', src='images/icons/iconic/raster/black/minus_alt_32x32.png')`

The icons to add and delete new columns are given a column of their own.  It is not outlined and the buttons are hidden until mouseover, so it is not apparent when editing column titles there exists another invisible column, making it appear there is unusable space.

**Comment by nickeeromo** [comment]
In script.js, each new column as it is being added is given 10% for width in a #icon-col.before statement.  One solution could be to remove the width property from that line and remove the width property from the line in index.jade for the width of the icon column.  But this would mean all the other columns will be as wide as their titles..

In my version I am writing, I put the icons at the top by the last column title and made them be displayed at all times, showing the use of that space.

**Comment by nickeeromo** [comment]
So without changing too much more of the code, you can just put the add / delete columns buttons somewhere else and add a display: none attribute to the #icon-col element.
