### ISSUE TITLE
Feature: Make colors of Postits configurable

### ISSUE THREAD

**Issue by moenka** [aliasaria/scrumblr#115]
As a user,
I want to decide which color the Postit has,
so I can use the color of the Postit as an indicator for special meanings (e.g. Task, Bug, Feature).

**Comment by ldidry** [comment]
It's available on Scrumblr's fork: [Framemo](https://framagit.org/framasoft/framemo) (which is fully translated in french, it may bother you)

**Comment by aliasaria** [comment]
Fixed in 1e4d964e5bbe93b505cbb7601f2e7302b2173285
