### ISSUE TITLE
HTTPS website and scrumblr iframe : mixed active content error

### ISSUE THREAD

**Issue by nylnook** [aliasaria/scrumblr#123]
Hi, and thanks for your great work on scrumblr !

We used your work for a welcome page on a shared wiki... ;)
But we just switched our website to HTTPS for security reason, and now we can't display an iframe coming from an http:// website, it's call a "mixed active content" and it's blocked by all major browsers...

Do you think you can host an https:/// version of Scrumblr ? Depending on your host, it's free with "Let's Encypt!".

Thanks a lot !

**Comment by mannyhuerta** [comment]
hey nylnook, i am hosting the react.js version of scrumblr at https://scrumblr.io

**Comment by nylnook** [comment]
Great @mannyhuerta ! Thanks a lot, I think we will move there shortly ;)
