### ISSUE TITLE
Eraser and Expo Marker Movement Bug

### ISSUE THREAD

**Issue by austinmm** [aliasaria/scrumblr#128]
**Operating System:** macOS Catilina
**Browser:** Safari V13.0.2
**Description:**
If I move the eraser or expo marker along the bottom of the board and then stretch or shrink the board's height the eraser and maker don't remain (follow) at the bottom of the board and instead, they stay put in their position (original bottom of the board position).

**Comment by lspevak** [comment]
This looks like really critical issue, so please look at my fork: [lspevak/scrumblr](https://github.com/lspevak/scrumblr).

**Comment by aliasaria** [comment]
Fixed in cb1475d4f40ea422c71a9596a7ae97b0cbcbb69a
