### ISSUE TITLE
scrumblr board does not show the plus & search buttons, so you can't add anything

### ISSUE THREAD

**Issue by mschark** [aliasaria/scrumblr#134]
when using scrumblr, I am missing the buttons on the lower left.
any special prerequists for them ?
the rest seems to wörd.
(no matter, what none IE browser I take)

**Comment by aliasaria** [comment]
Hmm they are using FontAwesome to appear, by applying the class:
"fa fa-expand fa-2x bottom-icon"

Maybe your browser doesn't support FontAwesome?

If you are able to add code, perhaps replacing them with an image is the best path. If not, feel free to file a bug with a screenshot and the exact version of your browser.

**Comment by wigy-opensource-developer** [comment]
Firefox 82 with enhanced tracking protection disables some font sites to avoid these font sites to collect data about what sites the user visits. I use the Decentraleyes addon to avoid such tracking, and I had to disable enhanced tracking protection on the scrumblr.ca site to download https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/fonts/fontawesome-webfont.woff?v=4.1.0
