### ISSUE TITLE
Board duplicates stickies over time

### ISSUE THREAD

**Issue by eltonrsmith** [aliasaria/scrumblr#160]
I've been preparing for a meeting for several days. I had the board all set up for the meeting today. When I checked my board, all my sticky notes are duplicated. The duplicates are stacked on top of each other. The number of duplicates may be the number of days since I worked on setting it up. This is a show stopper.

![scrumblrDOTca-BUG](https://user-images.githubusercontent.com/75268868/129903860-d43536c0-1602-49cc-a73f-8b777af32230.png)

Elton Smith in Portland OR

**Comment by aliasaria** [comment]
Hi Elton, nice to meet you. Is this happening for ALL the cards?

I am not seeing this locally. One thing I can guess is that the underlying networking tool that Scrumblr uses will try retrying if it things a request has failed. So I wonder if an action you took happened during a network blip, and that caused the system to duplicate items?

The other thing I could imagine is that the system is not handling your system disconnecting and reconnecting properly which could create an issue but it's hard to duplicate.

Sorry that this happened before a meeting -- I'll keep testing to see I can get this to happen for me.

**Comment by eltonrsmith** [comment]
Ali,

I was testing with 2 computers to simulate what would happen if people on
my team were also making changes to the board. I think that caused the
problem. I ended up using another tool.

Elton
