### ISSUE TITLE
Feature Request: Use GitHub issues

### ISSUE THREAD

**Issue by jbblanchet** [aliasaria/scrumblr#68]
I'd really like to be able to import and manipulate my issues in GitHub, ideally filtering by labels. Post-it could show the issue's title, and maybe the person it's assigned to and status. Double clicking on a Post-it would open the issue in GitHub for edition. New issues not yet placed on the board could go to the side. Scrumbler would simply remember the position of the issues on the board. Post-it color could be determined by secondary label, like pink for "bug" or blue for "new feature".

**Comment by mikegr** [comment]
+1

**Comment by sleepingscorpion** [comment]
+1
