### ISSUE TITLE
Not all colors can be selected

### ISSUE THREAD

**Issue by normkatz** [aliasaria/scrumblr#77]
The current version seems to only support 4 colors for new post-its: White, yellow, and two shades of greenish/blue even though the pallette is displayed on the bottom right and appears to be clickable.  I see the marker and eraser but it's not clear how to use the marker and color pallete in  the right order.  Am I doing something wrong or are certain colors just not supported?

**Comment by devekko** [comment]
yes, I clicked and clicked on the marker and eraser and it didnt work

fantastic demo system btw
