### ISSUE TITLE
Silly Question -- Is this entirely self-hosted?

### ISSUE THREAD

**Issue by woodrowbarlow** [aliasaria/scrumblr#91]
If I install this on my server, does it ever contact any external servers for anything?

**Comment by ocdtrekkie** [comment]
This is self-hosted. I've got a fork of it that runs on Sandstorm.io, which fully prohibits server apps from making outside calls. The only thing I think you'll find in the official version here, is it has Google Fonts on it still, I believe, which pulls fonts from Google servers. Easily fixed, of course.

**Comment by ocdtrekkie** [comment]
These commits are based on older code, but the changes should be the same.

Removing Google Fonts: https://github.com/ocdtrekkie/scrumblr/commit/901bf7eddc3f74b4bea04a5622e5050261dd3e96

Removing Google Analytics:
https://github.com/ocdtrekkie/scrumblr/commit/f936515f7845baa87b7a5077729451a3a85bfc68
